Traceback (most recent call last):
  File "/Users/olgahome/Documents/MLOps_course/MLOPS_Zoom_camp/Week_2/WandB/train.py", line 66, in <module>
    run_train()
  File "/Users/olgahome/opt/anaconda3/envs/wandb-env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/olgahome/opt/anaconda3/envs/wandb-env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/olgahome/opt/anaconda3/envs/wandb-env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/olgahome/opt/anaconda3/envs/wandb-env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/olgahome/Documents/MLOps_course/MLOPS_Zoom_camp/Week_2/WandB/train.py", line 41, in run_train
    artifact = wandb.use_artifact(data_artifact, type="preprocessed_dataset")
  File "/Users/olgahome/opt/anaconda3/envs/wandb-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 342, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/olgahome/opt/anaconda3/envs/wandb-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 332, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/olgahome/opt/anaconda3/envs/wandb-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2733, in use_artifact
    raise ValueError(
ValueError: You must pass an artifact name (e.g. "pedestrian-dataset:v1"), an instance of `wandb.Artifact`, or `wandb.Api().artifact()` to `use_artifact`